import {
  agentqlCapabilities,
  anthropicCapabilities,
  browserUseCapabilities,
  browserbaseCapabilities,
  cuaCapabilities,
  firecrawlCapabilities,
  hyperbrowserCapabilities,
  localCapabilities,
  midsceneCapabilities,
  nanobrowserCapabilities,
  openaiCapabilities,
  openhandsCapabilities,
  playwrightMcpCapabilities,
  skyvernCapabilities,
  stagehandCapabilities,
  steelCapabilities,
} from "./providers/capabilities";
import type { CapabilityMap, ProviderName } from "./core/types";

export interface ProviderMetadata {
  id: ProviderName;
  displayName: string;
  officialUrl: string;
  packageName: string | null;
  capabilities: CapabilityMap;
  environmentVariables: readonly string[];
  technicalStatus: "supported" | "experimental";
  notes: string;
  /** Matrix columns */
  openSource: boolean | "partial";
  browser: boolean;
  desktop: boolean | "partial";
  vision: boolean | "ai-assisted" | "dom-ai";
  api: boolean;
}

export const providers: readonly ProviderMetadata[] = [
  {
    id: "local",
    displayName: "Local (Playwright)",
    officialUrl: "https://playwright.dev",
    packageName: "playwright",
    capabilities: localCapabilities,
    environmentVariables: [],
    technicalStatus: "supported",
    notes: "Bundled Chromium + host shell/editor.",
    openSource: true,
    browser: true,
    desktop: "partial",
    vision: false,
    api: false,
  },
  {
    id: "cua",
    displayName: "TryCUA",
    officialUrl: "https://www.cua.ai",
    packageName: "@trycua/computer",
    capabilities: cuaCapabilities,
    environmentVariables: ["CUA_API_KEY"],
    technicalStatus: "supported",
    notes: "Desktop sandboxes. Browser partial via guest OS.",
    openSource: true,
    browser: true,
    desktop: true,
    vision: false,
    api: true,
  },
  {
    id: "openai",
    displayName: "OpenAI Computer Use",
    officialUrl: "https://platform.openai.com/docs/guides/tools-computer-use",
    packageName: "openai",
    capabilities: openaiCapabilities,
    environmentVariables: ["OPENAI_API_KEY"],
    technicalStatus: "supported",
    notes: "Model loop + local Playwright env (browser/desktop host).",
    openSource: false,
    browser: true,
    desktop: true,
    vision: true,
    api: true,
  },
  {
    id: "anthropic",
    displayName: "Anthropic Computer Use",
    officialUrl: "https://docs.anthropic.com/en/docs/agents-and-tools/computer-use",
    packageName: "@anthropic-ai/sdk",
    capabilities: anthropicCapabilities,
    environmentVariables: ["ANTHROPIC_API_KEY"],
    technicalStatus: "supported",
    notes: "computer_20250124 + bash + text editor over local env.",
    openSource: false,
    browser: true,
    desktop: true,
    vision: true,
    api: true,
  },
  {
    id: "browserbase",
    displayName: "Browserbase",
    officialUrl: "https://www.browserbase.com",
    packageName: "@browserbasehq/sdk",
    capabilities: browserbaseCapabilities,
    environmentVariables: ["BROWSERBASE_API_KEY", "BROWSERBASE_PROJECT_ID"],
    technicalStatus: "supported",
    notes: "Hosted browser over CDP.",
    openSource: false,
    browser: true,
    desktop: false,
    vision: false,
    api: true,
  },
  {
    id: "steel",
    displayName: "Steel.dev",
    officialUrl: "https://steel.dev",
    packageName: "steel-sdk",
    capabilities: steelCapabilities,
    environmentVariables: ["STEEL_API_KEY"],
    technicalStatus: "supported",
    notes: "Hosted browser infrastructure (CDP).",
    openSource: "partial",
    browser: true,
    desktop: false,
    vision: false,
    api: true,
  },
  {
    id: "hyperbrowser",
    displayName: "Hyperbrowser",
    officialUrl: "https://www.hyperbrowser.ai",
    packageName: "@hyperbrowser/sdk",
    capabilities: hyperbrowserCapabilities,
    environmentVariables: ["HYPERBROWSER_API_KEY"],
    technicalStatus: "supported",
    notes: "Hosted browser + agent APIs.",
    openSource: false,
    browser: true,
    desktop: false,
    vision: false,
    api: true,
  },
  {
    id: "browser-use",
    displayName: "Browser Use",
    officialUrl: "https://browser-use.com",
    packageName: "browser-use-sdk",
    capabilities: browserUseCapabilities,
    environmentVariables: ["BROWSER_USE_API_KEY"],
    technicalStatus: "supported",
    notes: "Best OSS agentic browser; cloud + CDP.",
    openSource: true,
    browser: true,
    desktop: false,
    vision: true,
    api: true,
  },
  {
    id: "skyvern",
    displayName: "Skyvern",
    officialUrl: "https://www.skyvern.com",
    packageName: null,
    capabilities: skyvernCapabilities,
    environmentVariables: ["SKYVERN_API_KEY"],
    technicalStatus: "supported",
    notes: "Production vision browser agents (REST).",
    openSource: true,
    browser: true,
    desktop: false,
    vision: true,
    api: true,
  },
  {
    id: "openhands",
    displayName: "OpenHands",
    officialUrl: "https://github.com/All-Hands-AI/OpenHands",
    packageName: null,
    capabilities: openhandsCapabilities,
    environmentVariables: ["OPENHANDS_API_KEY", "OPENHANDS_BASE_URL"],
    technicalStatus: "supported",
    notes: "Coding agent with browser; desktop partial.",
    openSource: true,
    browser: true,
    desktop: "partial",
    vision: true,
    api: true,
  },
  {
    id: "stagehand",
    displayName: "Stagehand",
    officialUrl: "https://github.com/browserbase/stagehand",
    packageName: "@browserbasehq/stagehand",
    capabilities: stagehandCapabilities,
    environmentVariables: ["BROWSERBASE_API_KEY", "BROWSERBASE_PROJECT_ID"],
    technicalStatus: "supported",
    notes: "Lightweight AI-assisted browser framework.",
    openSource: true,
    browser: true,
    desktop: false,
    vision: "ai-assisted",
    api: true,
  },
  {
    id: "agentql",
    displayName: "AgentQL",
    officialUrl: "https://www.agentql.com",
    packageName: "agentql",
    capabilities: agentqlCapabilities,
    environmentVariables: ["AGENTQL_API_KEY"],
    technicalStatus: "supported",
    notes: "DOM AI queries — strong for web apps.",
    openSource: "partial",
    browser: true,
    desktop: false,
    vision: "dom-ai",
    api: true,
  },
  {
    id: "midscene",
    displayName: "Midscene.js",
    officialUrl: "https://midscenejs.com",
    packageName: "@midscene/web",
    capabilities: midsceneCapabilities,
    environmentVariables: ["OPENAI_API_KEY"],
    technicalStatus: "supported",
    notes: "Vision AI browser automation (growing fast).",
    openSource: true,
    browser: true,
    desktop: false,
    vision: true,
    api: true,
  },
  {
    id: "nanobrowser",
    displayName: "Nanobrowser",
    officialUrl: "https://github.com/nanobrowser/nanobrowser",
    packageName: null,
    capabilities: nanobrowserCapabilities,
    environmentVariables: ["NANOBROWSER_CDP_URL", "NANOBROWSER_API_KEY"],
    technicalStatus: "experimental",
    notes: "Experimental agentic browser (CDP bridge).",
    openSource: true,
    browser: true,
    desktop: false,
    vision: true,
    api: true,
  },
  {
    id: "playwright-mcp",
    displayName: "Playwright MCP",
    officialUrl: "https://github.com/microsoft/playwright-mcp",
    packageName: "playwright",
    capabilities: playwrightMcpCapabilities,
    environmentVariables: [],
    technicalStatus: "supported",
    notes: "Playwright with MCP-aligned tool names.",
    openSource: true,
    browser: true,
    desktop: false,
    vision: false,
    api: true,
  },
  {
    id: "firecrawl",
    displayName: "Firecrawl",
    officialUrl: "https://www.firecrawl.dev",
    packageName: "@mendable/firecrawl-js",
    capabilities: firecrawlCapabilities,
    environmentVariables: ["FIRECRAWL_API_KEY"],
    technicalStatus: "supported",
    notes: "Scrape/crawl/map/search (web data, not live UI).",
    openSource: "partial",
    browser: false,
    desktop: false,
    vision: false,
    api: true,
  },
];

/** Compact matrix for docs / landing. */
export function providerMatrix() {
  return providers.map((p) => ({
    id: p.id,
    name: p.displayName,
    openSource: p.openSource,
    browser: p.browser,
    desktop: p.desktop,
    vision: p.vision,
    api: p.api,
    status: p.technicalStatus,
  }));
}
