import { defineConfig } from "tsdown";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/metadata.ts",
    "src/testing/index.ts",
    "src/providers/local/index.ts",
    "src/providers/browserbase/index.ts",
    "src/providers/browser-use/index.ts",
    "src/providers/cua/index.ts",
    "src/providers/firecrawl/index.ts",
    "src/providers/openai/index.ts",
    "src/providers/anthropic/index.ts",
    "src/providers/steel/index.ts",
    "src/providers/hyperbrowser/index.ts",
    "src/providers/skyvern/index.ts",
    "src/providers/openhands/index.ts",
    "src/providers/stagehand/index.ts",
    "src/providers/agentql/index.ts",
    "src/providers/midscene/index.ts",
    "src/providers/nanobrowser/index.ts",
    "src/providers/playwright-mcp/index.ts",
  ],
  format: "esm",
  dts: true,
  sourcemap: true,
  clean: true,
  external: [
    "playwright",
    "@browserbasehq/sdk",
    "@browserbasehq/stagehand",
    "browser-use-sdk",
    "@trycua/computer",
    "@mendable/firecrawl-js",
    "openai",
    "@anthropic-ai/sdk",
    "steel-sdk",
    "@hyperbrowser/sdk",
    "agentql",
    "@midscene/web",
  ],
});
